### ISSUE TITLE
Requesting Tutorial Jupyter Notebook

### ISSUE THREAD

**Issue by defencedog** [dahyun-kang/newoptpy#1]
Can author plz upload a notebook showcasing how to use different methods?

**Comment by dahyun-kang** [comment]
Hello

I am afraid that I do not plan to update/manage this repo unless a severe bug is found.
At this point, I recommend you to try with the python script as described in [README](https://github.com/dahyun-kang/newoptpy#runner-example-run).

Have a great day! 😃 


Best,
Dahyun

**Comment by dahyun-kang** [comment]
Closing the issue.
